Feature/give possibility to not download the dataset qualities
openml/openml-python pull request #1017
Opened 2021-01-12 10:40 UTC by a-moadel

#### Reference Issue

#### What does this PR implement/fix? Explain your changes.
We can Ignore downloading the dataset qualities if its not exist while getting datasets.

#### How should this PR be tested?
Clear the cache , and calling get_dataset with download_qualities set to false : this result in qulaities.xml to not be downloaded.
Clear the cache , and calling get_dataset with download_qualities set to default : this result in qulaities.xml to be downloaded.

#### Any other comments?

2021-01-12 13:31 UTC, PGijsbers requested changes
@mfeurer Do you think the qualities should be loaded if they are present in cache? That would mean different results of the function depending on the cache state. I would think we can skip it altogether?
@a-moadel Please also add unit tests that test the feature works as intended (after we agree on the desired behavior).

I noticed the `pre-commit` workflow is not triggered. Does anyone have an idea why this would not trigger?

Closes #1009.

2021-01-12 13:31 UTC, PGijsbers commented on openml/datasets/functions.py
> +    download_qualities : bool, optional
```suggestion
    download_qualities : bool, optional (default=True)
```

2021-01-12 13:31 UTC, PGijsbers commented on openml/datasets/functions.py
> +    download_qualities : bool, optional
```suggestion
    download_qualities : bool, optional (default=True)
```

2021-01-27 08:56 UTC, mfeurer commented
This looks good to me now. @PGijsbers you had a comment about persistent behavior, that's not yet addressed, right?

2021-02-10 14:20 UTC, PGijsbers requested changes
First off, sorry for the delay. I think it works as intended now 🥳 however I do have a few minor comments that I would prefer to see addressed before merging. I'd like to see references to the old behavior updated, and I suggested a minor code change which puts the responsibility of not loading `qualities` in the `get_dataset` function instead. I don't think it makes sense to pass down a `bool` that signifies you just want `""` back - then we don't need to call down in the first place.

2021-02-10 14:20 UTC, PGijsbers commented on tests/test_datasets/test_dataset_functions.py
> +        qualities = _get_dataset_qualities_file(self.workdir, 2, False)
Could you use keywords here (e.g. `download_qualities=False`)?

2021-02-10 14:20 UTC, PGijsbers commented on openml/datasets/functions.py
> +            qualities_file = _get_dataset_qualities_file(
I think it makes more sense to use `download_qualities` here and not call the `_get_dataset_qualities_file` if we don't want to process the qualities.

2021-02-10 14:20 UTC, PGijsbers commented on openml/datasets/functions.py
> +        If `True`, also download qualities.xml file. If false use the file if it was cached.
Please update this and the other references where it says the cached version is used if `false` is passed, as this is not the behavior anymore.

2021-02-11 10:07 UTC, PGijsbers approved these changes

2021-02-11 10:07 UTC, merged