improve path detection
openml/openml-python pull request #1021
Opened 2021-02-04 12:27 UTC by mfeurer

Fixes an issue that could make unit tests crashed if the OpenML-Python repository was not in the path. Reported in https://github.com/conda-forge/staged-recipes/pull/13860

2021-02-10 14:26 UTC, PGijsbers approved these changes

2021-02-10 14:28 UTC, PGijsbers commented
It looks like the tests are now leaving files behind: e.g. https://github.com/openml/openml-python/pull/1021/checks?check_run_id=1830686974

2021-02-11 11:02 UTC, PGijsbers requested changes
setting to request changes because the issue needs to be looked into.

2021-02-11 21:00 UTC, mfeurer commented
Hm, I don't understand why my change might fix this, but it appears to do so?

2021-02-12 09:50 UTC, PGijsbers approved these changes

2021-02-12 09:50 UTC, merged