API for topics
openml/openml-python pull request #1023
Opened 2021-02-15 08:56 UTC by sahithyaravi1493

#### Reference Issue

#### What does this PR implement/fix? Explain your changes.
Topic APIs - For adding topics for datasets based on a topic  model
topic_add - to add a topic to a dataset
topic_delete - to delete a topic added to a dataset
We are going to use this in the new website to group datasets/filter datasets by topic. 

This API can be accessed only by **admin users.**
In future, we will add a get API to get topics per dataset or list datasets by topic.

#### How should this PR be tested?

#### Any other comments?
Since the API can only be used by admin, I tested this locally with the admin key to see if it works.
The unit test added only checks if an error occurs when a non-admin user accesses these APIs.

2021-02-15 12:51 UTC, PGijsbers requested changes
I think these functions should be marked private (i.e. underscore prefix and not imported/added to `__all__` in `__init__.py` to avoid accidental imports). This allows the code itself to signal to users that it shouldn't be used by them.

Not writing an example is fine, given we don't expect a regular user to use this functionality. However, for later reference it might be good to add a section to the `api` documentation with admin-only functions.

I would like @mfeurer to weigh in on this though. What are your thoughts on how to add admin-only operations? The main alternative I considered would be to perhaps add a separate submodule for them, but as long as there aren't many of them this makes more sense to me.

2021-02-17 20:36 UTC, mfeurer commented
> I would like @mfeurer to weigh in on this though. What are your thoughts on how to add admin-only operations? The main alternative I considered would be to perhaps add a separate submodule for them, but as long as there aren't many of them this makes more sense to me.

I don't have a strong opinion on this, but it looks like it would be a bit nicer in a separate admins package.

2021-03-02 09:50 UTC, PGijsbers commented
Okay, in that case I propose to just go with the private methods for now, and refactor to an `admin` package when we have more admin features.

2021-03-09 10:41 UTC, PGijsbers approved these changes

2021-03-09 10:42 UTC, merged