Fix documentation links
openml/openml-python pull request #1048
Opened 2021-04-07 09:14 UTC by mfeurer

This aims to fix broken links in the documentation. In order to do so it does:

* make warnings during documentation building fail the build process
* fix all warnings to make the build process pass
* check for links to work via the [w3 validator](https://validator.w3.org/checklink?uri=https%3A%2F%2Fopenml.github.io%2Fopenml-python%2Fmaster&hide_type=all&recursive=on&depth=&check=Check)

In the process of creating this PR I opened #1046 and #1047 so we can in the future fully automate the process of checking the docs for broken links.

2021-04-09 07:33 UTC, PGijsbers requested changes
Thanks! Automating checking for broken links is awesome :) 
Few questions:
 - I built the docs locally, but did not check all the links work - is that alright?
 - What stops us from referencing numpy docs to turn nitpicky on? 
 - Could you add this work to  `progress.rst`?

2021-04-09 08:50 UTC, mfeurer commented
> I built the docs locally, but did not check all the links work - is that alright?

Yes, you need to explicitly do `make linkcheck`

> What stops us from referencing numpy docs to turn nitpicky on?

The fact that this already took me too long and I didn't have time any more ;) I think nitpicky also complained about the task type enum which I didn't know how to fix.

> Could you add this work to progress.rst?

Sure.

2021-04-09 13:59 UTC, PGijsbers commented
The doc jobs fail.

2021-04-09 14:10 UTC, mfeurer commented
> The doc jobs fail.

Yes, the rebase on #1044 made it fail :( I'll be working on that soonish, but probably not this week any more...

2021-04-19 09:39 UTC, PGijsbers requested changes
Let's use the built-in function for generating openml urls. A bit less daunting and, at least as important, more future proof.

2021-04-19 09:39 UTC, PGijsbers commented on examples/20_basic/introduction_tutorial.py
> +print(f"kNN on {data.name}: https://test.openml.org/r/{myrun.run_id}")
```suggestion
print(f"kNN on {data.name}: {myrun.openml_url}")
```

2021-04-19 09:39 UTC, PGijsbers commented on examples/20_basic/simple_flows_and_runs_tutorial.py
> +print("The flow can be found at https://test.openml.org/f/" + str(myrun.flow_id))
```suggestion
print(f"Run was uploaded to {myrun.openml_url}")
print(f"The flow can be found at {myrun.flow.openml_url}")
```

2021-04-19 09:39 UTC, PGijsbers commented on examples/30_extended/flows_and_runs_tutorial.py
> +print("Uploaded to https://test.openml.org/r/" + str(myrun.run_id))
```suggestion
print(f"Uploaded to {myrun.openml_url}")
```

2021-04-19 09:39 UTC, PGijsbers commented on examples/30_extended/flows_and_runs_tutorial.py
> +print("Uploaded to https://test.openml.org/r/" + str(myrun.run_id))
```suggestion
print(f"Uploaded to {myrun.openml_url}")
```

2021-04-19 09:39 UTC, PGijsbers commented on examples/30_extended/flows_and_runs_tutorial.py
> +print("Uploaded to https://test.openml.org/r/" + str(myrun.run_id))
```suggestion
print(f"Uploaded to {myrun.openml_url}")
```

2021-04-19 09:39 UTC, PGijsbers commented on examples/30_extended/flows_and_runs_tutorial.py
> +    print(f"kNN on {data.name}: https://test.openml.org/r/{myrun.run_id}")
```suggestion
    print(f"kNN on {data.name}: {myrun.openml_url}")
```

2021-04-20 18:06 UTC, mfeurer commented
Great suggestion, just applied it!

2021-04-21 09:38 UTC, PGijsbers approved these changes
LGTM 🎉

2021-04-21 09:39 UTC, merged