refactor: Deprecate array formats and default to dataframe
openml/openml-python pull request #1372
Opened 2024-10-16 16:10 UTC by eddiebergman

WIP

2025-04-01 13:39 UTC, SubhadityaMukherjee approved these changes
Okay looks good to me now. Merge conflicts were fixed, target_names was renamed back to target since I could not find a reason to change it everywhere.

2025-04-01 13:40 UTC, SubhadityaMukherjee commented
I am not confident in trying to merge it to develop until the tests are up and running again.

2025-06-16 09:15 UTC, LennartPurucker reviewed
Did one full pass, LGTM, now looking into tests

2025-06-17 11:57 UTC, PGijsbers commented on tests/test_datasets/test_dataset_functions.py
> +            # Maybe index?
Make the `did` the index to the dataframe rows?

2025-06-17 12:47 UTC, PGijsbers requested changes
Pretty much fine to merge

2025-06-17 12:47 UTC, PGijsbers commented on openml/setups/functions.py
> +    if output_format not in ["dataframe", "object"]:
Is there a reason we don't deprecate `'object'` here?

2025-06-17 12:47 UTC, PGijsbers commented on openml/utils.py
> +            if n_recieved >= LIMIT:
```suggestion
            n_received = sum(len(result) for result in results)
            if n_received >= LIMIT:
```

2025-06-17 12:47 UTC, PGijsbers commented on openml/utils.py
> +                batch_size = LIMIT - n_recieved
```suggestion
            if LIMIT - n_received < BATCH_SIZE_ORIG:
                batch_size = LIMIT - n_received
```

2025-06-17 12:47 UTC, PGijsbers commented on openml/setups/setup.py
> +# TODO(eddiebergman): All functionality handled by dataclass
```suggestion
```

2025-06-17 12:47 UTC, PGijsbers commented on openml/setups/setup.py
> +# TODO(eddiebergman): All functionality handled by dataclass
```suggestion
```

2025-06-17 12:47 UTC, PGijsbers commented on openml/setups/setup.py
> +# TODO(eddiebergman): All functionality handled by dataclass
We can open an issue for this if desired. But dataclasses don't handle type validation, have a different representation, so in the end you would have most of this anyway. Pydantic may be a nicer way to handle some of this, but then we would add an extra dependency.

2025-06-17 13:02 UTC, LennartPurucker commented on tests/test_datasets/test_dataset_functions.py
> +            # Maybe index?
I do not get this point, please elaborate.

2025-06-17 13:03 UTC, LennartPurucker commented on openml/setups/functions.py
> +    if output_format not in ["dataframe", "object"]:
Not sure, seems from some older use case. Uniquely different from dict. I would keep it for now and maybe refactor it later.

2025-06-17 13:06 UTC, merged