Improved documentation of example
openml/openml-python pull request #960
Opened 2020-10-16 22:35 UTC by joaquinvanschoren

#### What does this PR implement/fix? Explain your changes.
The dataset creation example did not explain how to add multiple ignore attributes.

I tried comma-separated but then the server doesn't recognize them (but also doesn't return an error).
It needs to be a list.

2020-10-19 11:23 UTC, PGijsbers commented on examples/30_extended/create_upload_tutorial.py
> +    # identifiers and indexes. E.g. ["feat1","feat2"]
```suggestion
    # Attribute or list of attributes that should be excluded in modelling, such as 
    # identifiers and indexes. E.g. "feat1" or ["feat1","feat2"]
```

2020-10-19 11:24 UTC, PGijsbers commented on examples/30_extended/create_upload_tutorial.py
> +    # identifiers and indexes. E.g. ["feat1","feat2"]
My suggestion to reflect that it can be either a single attribute or a list of attributes (and change "array" to "list").

2020-10-19 11:25 UTC, PGijsbers requested changes
Please look at my suggested change and commit it if you feel it improves the PR. Either way works for me.

2020-10-19 11:25 UTC, mfeurer commented
The docs suggest that this can be a string or a list. Should we maybe take you running into this issue as a reason to check if the attributes actually exist?

2020-10-19 11:27 UTC, PGijsbers commented
Missed that detail of the original post. Agreed that we should also add a check to verify the attributes actually exist 👍

2020-10-22 08:03 UTC, PGijsbers approved these changes

2020-10-22 08:03 UTC, merged