Dev master merged
openml/openml-python pull request #970
Opened 2020-10-25 09:14 UTC by PGijsbers

Resolves merge conflicts that prevent `develop` from being merged with `master`.

2020-10-25 09:39 UTC, mfeurer requested changes

2020-10-25 09:39 UTC, mfeurer commented on tests/conftest.py
> +# License: BSD 3-Clause
There's a duplicate license header now.

2020-10-25 09:56 UTC, mfeurer approved these changes

2020-10-25 16:08 UTC, merged

2020-11-02 16:32 UTC, joaquinvanschoren commented
@all-contributors please add @pgijsbers for code